### ISSUE TITLE
Local dataset - persisting the graph; what might the format be?

### ISSUE THREAD

**Issue by grdw** [quintel/atlas#59]
The graph is as specified in a yaml format. But in which format must this graph be in order for it to be actually usuable for `ETEngine`. 

I'm currently thinking that it's:

```yaml
nodes:
  node_a:
    demand: 1
  node_b:
    demand: 1
edges:
  node_a-node_b@test:
    child_share: 1
```

But I'm not sure if this is the way to go? Also, I'm not sure which attribute to pick, is it always the case that it's `demand`, `max_demand`, `child_share` or `parent_share`? Or are there other attributes which need to be exported aswell?
